[workspace]
resolver = "2"
members = [
    "fuzz",
    "pastelito-core",
    "pastelito-model",
    "pastelito-vscode"
]

[workspace.package]
license = "MIT"

[profile.release-with-debug]
inherits = "release"
debug = true
