[package]
name = "pastelito-model"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
speedy = "0.8.7"
pastelito-data = { path = "../pastelito-data" }

[build-dependencies]
serde_json = "1.0.128"
speedy = "0.8.7"
pastelito-data = { path = "../pastelito-data" }
